const errorCodes = {
  INVALID_DATA: 'INVALID_DATA',
  INVALID_TYPE: 'INVALID_TYPE',
  DOUBLE_REPORT: 'DOUBLE_REPORT',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  MEASURE_NOT_FOUND: 'MEASURE_NOT_FOUND',
  MEASURES_NOT_FOUND: 'MEASURES_NOT_FOUND',
  CONFIRMATION_DUPLICATED: 'CONFIRMATION_DUPLICATE',
}

export default errorCodes
